---
# handlers file for flexget-daemon
- name: Reload flexget daemon
  ansible.builtin.command:
    cmd: "{{ flexget_daemon_venv_path }}/bin/flexget daemon reload-config"
  changed_when: false

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
